Code doesn't compile.
Error : mpz_poly.c:588:43: error: ‘rc’ may be used uninitialized in this function [-Werror=maybe-uninitialized]
Problem is that I'm just not sure how to correct this one. (I'm trying to see)
I had to solve conflicts yesterday, I started to make changes before seeing you, and I didn't commit them -> conflict
I came back to the state there was right before I started to change anything, and then I merged.
Don't really now if this changed something else or not, I couldn't test it yet.